from enum import Enum


class Errorcode(str, Enum):
    TITLE_REQUIRED="TITLE_REQUIRED"
    AUTHOR_ID_REQUIRED="AUTHOR_ID_REQUIRED"
    AUTHOR_NOT_FOUND="AUTHOR_NOT_FOUND"
    ISBN_REQUIRED="ISBN_REQUIRED"
    LANGUAGE_ID_REQUIRED="LANGUAGE_REQUIRED"
    DESCRIPTION_REQUIRED="DESCRIPTION_REQUIRED"

    