"""Add deactivated at column to users

Revision ID: 2d263caa7385
Revises: b7e3b258de29
Create Date: 2025-03-11 10:09:07.557189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d263caa7385'
down_revision: Union[str, None] = 'b7e3b258de29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deactivated_at')
    # ### end Alembic commands ###
